
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PR_BETRAYAL = 33;
  public static final int PR_STRATEGY = 10;
  public static final int PR_STRATEGIES = 27;
  public static final int PR_SCORING = 28;
  public static final int ENTERO = 21;
  public static final int DOS_PUNTOS = 15;
  public static final int PR_IF = 5;
  public static final int COR_DER = 19;
  public static final int PR_ROUNDS = 25;
  public static final int PR_ELSE = 7;
  public static final int PR_PUNISHMENT = 34;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int PR_THEN = 6;
  public static final int OR = 3;
  public static final int PR_SEED = 13;
  public static final int LLAV_IZQ = 16;
  public static final int ID = 24;
  public static final int PR_INITIAL = 9;
  public static final int EOF = 0;
  public static final int PR_PLAYERS = 26;
  public static final int EQUAL = 23;
  public static final int error = 1;
  public static final int COMA = 14;
  public static final int PR_WITH = 12;
  public static final int ACCION = 22;
  public static final int PR_COOPERATION = 32;
  public static final int PR_MATCH = 35;
  public static final int PR_RULES = 8;
  public static final int PR_RUN = 11;
  public static final int COR_IZQ = 18;
  public static final int PR_MUTUAL = 29;
  public static final int BOOLEANO = 20;
  public static final int LLAV_DER = 17;
  public static final int PR_REWARD = 31;
  public static final int PR_DEFECTION = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "PR_IF",
  "PR_THEN",
  "PR_ELSE",
  "PR_RULES",
  "PR_INITIAL",
  "PR_STRATEGY",
  "PR_RUN",
  "PR_WITH",
  "PR_SEED",
  "COMA",
  "DOS_PUNTOS",
  "LLAV_IZQ",
  "LLAV_DER",
  "COR_IZQ",
  "COR_DER",
  "BOOLEANO",
  "ENTERO",
  "ACCION",
  "EQUAL",
  "ID",
  "PR_ROUNDS",
  "PR_PLAYERS",
  "PR_STRATEGIES",
  "PR_SCORING",
  "PR_MUTUAL",
  "PR_DEFECTION",
  "PR_REWARD",
  "PR_COOPERATION",
  "PR_BETRAYAL",
  "PR_PUNISHMENT",
  "PR_MATCH"
  };
}

