
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PR_THEN = 6;
  public static final int AND = 2;
  public static final int OR = 3;
  public static final int EQUAL = 20;
  public static final int ACCION = 19;
  public static final int NOT = 4;
  public static final int LLAV_IZQ = 13;
  public static final int ID = 21;
  public static final int BOOLEANO = 17;
  public static final int PR_STRATEGY = 10;
  public static final int LLAV_DER = 14;
  public static final int DOS_PUNTOS = 12;
  public static final int PR_IF = 5;
  public static final int COMA = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PR_RULES = 8;
  public static final int PR_INITIAL = 9;
  public static final int COR_IZQ = 15;
  public static final int ENTERO = 18;
  public static final int COR_DER = 16;
  public static final int PR_ELSE = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "PR_IF",
  "PR_THEN",
  "PR_ELSE",
  "PR_RULES",
  "PR_INITIAL",
  "PR_STRATEGY",
  "COMA",
  "DOS_PUNTOS",
  "LLAV_IZQ",
  "LLAV_DER",
  "COR_IZQ",
  "COR_DER",
  "BOOLEANO",
  "ENTERO",
  "ACCION",
  "EQUAL",
  "ID"
  };
}

